# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(arrow)
library(bslib)
library(DT)
library(duckdb)
library(ggplot2)
library(plotly)
library(rhino)
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyjs)
library(treesitter)
library(treesitter.r)
