#!/usr/bin/env Rscript

#### TODO: this is to be combined with original conversion file for Williams to replace the expression.parquet files generated.
# expression.parquet files generated by older original script has been renamed to expression_woutMOESM2.parquet as it doesn't include the marker gene XLSX

# Convert Williams Seeker2023 Excel workbooks into expression.parquet files,
# appending into the existing per-lineage conversion folders so the registry
# YAML and dataset list require no changes.
#
# Folder layout (already exists):
#   <output_root>/
#     01_HCA_all_celltypes/      ← MOESM4 (all lineages) + MOESM5 appended here
#     02_HCA_oligodendroglia/    ← MOESM2 "Oligodendroglia" sheet appended here
#     03_HCA_astrocytes/         ← MOESM2 "Astrocytes" sheet appended here
#     04_HCA_microglia/          ← MOESM2 "Microglia_Macrophages" sheet appended here
#     05_HCA_vascular_cells/     ← MOESM2 "Vascular_Cells" sheet appended here
#     06_HCA_neurons/            ← MOESM2 "Neurons" sheet appended here
#     07_HCA_oligos_opcs_LS/     ← MOESM2 "Oligos_OPCs_LS" sheet appended here
#
# Each expression.parquet gains three new columns on top of whatever was
# already written by the old script:
#   covariate_type  — "cluster_marker" | "condition" | "clusterwise_condition"
#   cluster_id      — fine cluster label (Astrocytes_1, AS_1 …)  or NA
#   cluster_description — covariate context ("tissue", "CB — Tissue" …) or NA
#
# Run:
#   Rscript williams_xlsx_to_parquet.R <moesm2.xlsx> <moesm4.xlsx> <moesm5.xlsx> [output_root]
#
# Dev note: delete all existing expression.parquet files before running so
# there is no risk of double-appending rows from a previous run.

`%||%` <- function(a, b) if (is.null(a)) b else a

# ---------------------------------------------------------------------------
# Folder ↔ cell-type mappings  (normalised keys → folder names)
# ---------------------------------------------------------------------------

LINEAGE_FOLDERS <- c(
  oligodendroglia      = "02_HCA_oligodendroglia",
  astrocytes           = "03_HCA_astrocytes",
  microglia_macrophages = "04_HCA_microglia",
  vascular_cells       = "05_HCA_vascular_cells",
  neurons              = "06_HCA_neurons",
  oligos_opcs_ls       = "07_HCA_oligos_opcs_LS"
)

normalise_key <- function(x) {
  gsub("[^A-Za-z0-9]+", "_", tolower(trimws(as.character(x))))
}

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

#' Read an Excel sheet and drop phantom row-name first columns.
#' The first column is kept as `gene` when it contains non-numeric values
#' (i.e. actual gene names stored as Excel row names) and dropped only when
#' it is purely numeric (Excel auto-row-numbers) or duplicates the gene column.
read_sheet <- function(xlsx_path, sheet) {
  df <- readxl::read_xlsx(xlsx_path, sheet = sheet, col_types = "text")
  first <- names(df)[1]

  is_phantom <- grepl("^\\.\\.\\.[0-9]+$", first) || first == "" || first == "X"
  if (!is_phantom) return(df)

  names(df)[1] <- ".row_id"
  values <- df$.row_id

  # If the column is purely numeric it is just Excel row numbers — drop it.
  # If it contains gene-name-like strings, rename it to `gene` (or drop if
  # a `gene` column already exists and matches).
  all_numeric <- !any(is.na(suppressWarnings(as.numeric(values[!is.na(values)]))))

  if (all_numeric) {
    df$.row_id <- NULL
  } else if ("gene" %in% names(df)) {
    df$.row_id <- NULL          # redundant — real gene column already present
  } else {
    names(df)[names(df) == ".row_id"] <- "gene"
  }

  df
}

#' Build a canonical expression data frame from raw column vectors.
#' Scalar values are recycled to length(gene_symbol).
make_expression_df <- function(
    gene_symbol,
    log2fc              = NA_real_,
    pvalue              = NA_real_,
    padj                = NA_real_,
    pct_expressed_a     = NA_real_,
    pct_expressed_b     = NA_real_,
    cell_type           = NA_character_,
    cluster_id          = NA_character_,
    cluster_description = NA_character_,
    covariate_type      = NA_character_,
    condition_a         = NA_character_,
    condition_b         = NA_character_) {

  n <- length(gene_symbol)
  s <- function(x) if (length(x) == 1L) rep(x, n) else x

  data.frame(
    gene_symbol         = as.character(gene_symbol),
    organism            = "human",
    log2fc              = suppressWarnings(as.numeric(s(log2fc))),
    pvalue              = suppressWarnings(as.numeric(s(pvalue))),
    padj                = suppressWarnings(as.numeric(s(padj))),
    pct_expressed_a     = suppressWarnings(as.numeric(s(pct_expressed_a))),
    pct_expressed_b     = suppressWarnings(as.numeric(s(pct_expressed_b))),
    cell_type           = as.character(s(cell_type)),
    cluster_id          = as.character(s(cluster_id)),
    cluster_description = as.character(s(cluster_description)),
    covariate_type      = as.character(s(covariate_type)),
    condition_a         = as.character(s(condition_a)),
    condition_b         = as.character(s(condition_b)),
    stringsAsFactors    = FALSE
  )
}

#' Append new rows to an existing expression.parquet, or write fresh if absent.
#' Adds any missing columns (filled NA) so old and new rows always align.
append_expression_parquet <- function(new_df, output_dir) {
  path <- file.path(output_dir, "expression.parquet")

  if (file.exists(path)) {
    existing <- arrow::read_parquet(path)

    # Add missing columns to whichever side lacks them
    for (col in setdiff(names(new_df), names(existing)))
      existing[[col]] <- NA
    for (col in setdiff(names(existing), names(new_df)))
      new_df[[col]] <- NA

    combined <- rbind(existing[, names(new_df)], new_df)
  } else {
    combined <- new_df
  }

  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  arrow::write_parquet(combined, path, compression = "snappy")
  message("  appended ", nrow(new_df), " rows → ", path)
  invisible(path)
}

# ---------------------------------------------------------------------------
# MOESM2 — cluster marker genes
# ---------------------------------------------------------------------------
# Columns: p_val  avg_log2FC  pct.1  pct.2  p_val_adj  cluster  gene
#   sheet name  → cell_type  (broad lineage)
#   cluster     → cluster_id (fine label: "Astrocytes_1")
#   condition_a/b = NA  (no between-condition comparison)
#
# Each sheet is appended to the matching lineage folder only.
# Sheets with no matching folder are skipped with a warning.

convert_williams_MOESM2 <- function(xlsx_path, output_root) {
  sheets <- readxl::excel_sheets(xlsx_path)

  for (sheet in sheets) {
    key    <- normalise_key(sheet)
    folder <- LINEAGE_FOLDERS[key]

    if (is.na(folder)) {
      warning("MOESM2: no folder mapping for sheet '", sheet, "' (key='", key, "') — skipped")
      next
    }

    df  <- read_sheet(xlsx_path, sheet)
    out <- make_expression_df(
      gene_symbol         = df$gene,
      log2fc              = df$avg_log2FC,
      pvalue              = df$p_val,
      padj                = df$p_val_adj,
      pct_expressed_a     = df$pct.1,
      pct_expressed_b     = df$pct.2,
      cell_type           = sheet,
      cluster_id          = df$cluster,
      cluster_description = NA_character_,
      covariate_type      = "cluster_marker",
      condition_a         = NA_character_,
      condition_b         = NA_character_
    )

    append_expression_parquet(out, file.path(output_root, folder))
  }
}

# ---------------------------------------------------------------------------
# MOESM4 — DE with region, age and sex
# ---------------------------------------------------------------------------
# Sheet "All_Celltypes" columns:
#   p_val  avg_log2FC  pct.1  pct.2  p_val_adj  cluster  gene  cell_lineage  variable
#   cluster      → condition_a         (region label: "BA4", "CSC" …)
#   variable     → cluster_description (covariate tested: "tissue", "age", "sex")
#   cell_lineage → cell_type
#
# Sheet "OPC_BA4_vs_CSC":
#   no cluster/gene/cell_lineage columns — stats only
#   hardcoded condition_a="BA4", condition_b="CSC", cell_type="oligos_opcs_ls"
#
# All rows go to 01_HCA_all_celltypes.
# Additionally, rows are filtered by cell_lineage and appended to each
# matching lineage folder so per-lineage datasets also contain this DE data.

convert_williams_MOESM4 <- function(xlsx_path, output_root) {

  all_raw <- read_sheet(xlsx_path, "All_Celltypes")
  all_df  <- make_expression_df(
    gene_symbol         = all_raw$gene,
    log2fc              = all_raw$avg_log2FC,
    pvalue              = all_raw$p_val,
    padj                = all_raw$p_val_adj,
    pct_expressed_a     = all_raw$pct.1,
    pct_expressed_b     = all_raw$pct.2,
    cell_type           = all_raw$cell_lineage,
    cluster_id          = NA_character_,
    cluster_description = all_raw$variable,
    covariate_type      = "condition",
    condition_a         = all_raw$cluster,
    condition_b         = NA_character_
  )

  opc_raw <- read_sheet(xlsx_path, "OPC_BA4_vs_CSC")
  opc_df  <- make_expression_df(
    gene_symbol         = opc_raw$gene %||% seq_len(nrow(opc_raw)),
    log2fc              = opc_raw$avg_log2FC,
    pvalue              = opc_raw$p_val,
    padj                = opc_raw$p_val_adj,
    pct_expressed_a     = opc_raw$pct.1,
    pct_expressed_b     = opc_raw$pct.2,
    cell_type           = "oligos_opcs_ls",
    cluster_id          = NA_character_,
    cluster_description = "tissue",
    covariate_type      = "condition",
    condition_a         = "BA4",
    condition_b         = "CSC"
  )

  combined <- rbind(all_df, opc_df)

  # All rows → 01_HCA_all_celltypes
  append_expression_parquet(combined, file.path(output_root, "01_HCA_all_celltypes"))

  # Per-lineage rows → matching lineage folders
  lineage_keys <- normalise_key(combined$cell_type)
  for (key in names(LINEAGE_FOLDERS)) {
    idx <- which(lineage_keys == key)
    if (length(idx) == 0L) next
    append_expression_parquet(combined[idx, ], file.path(output_root, LINEAGE_FOLDERS[[key]]))
  }
}

# ---------------------------------------------------------------------------
# MOESM5 — cluster-wise DE with region, age and sex
# ---------------------------------------------------------------------------
# Sheet "Table_S6" columns:
#   p_val  avg_log2FC  pct.1  pct.2  p_val_adj  cluster  gene  clu  variable
#   clu      → cluster_id          (fine Leiden cluster: "AS_1", "Oligo_F" …)
#   cluster  → condition_a         (region label: "CB", "BA4" …)
#   variable → kept separately; combined with cluster into cluster_description
#              as "CB — Tissue" so both pieces are readable in one column
#
# All rows go to 01_HCA_all_celltypes only (no cell_lineage column in this sheet).

convert_williams_MOESM5 <- function(xlsx_path, output_root) {
  df <- read_sheet(xlsx_path, "Table_S6")

  cluster_desc <- paste0(
    trimws(as.character(df$cluster)), " \u2014 ",
    trimws(as.character(df$variable))
  )

  out <- make_expression_df(
    gene_symbol         = df$gene,
    log2fc              = df$avg_log2FC,
    pvalue              = df$p_val,
    padj                = df$p_val_adj,
    pct_expressed_a     = df$pct.1,
    pct_expressed_b     = df$pct.2,
    cell_type           = NA_character_,
    cluster_id          = df$clu,
    cluster_description = cluster_desc,
    covariate_type      = "clusterwise_condition",
    condition_a         = df$cluster,
    condition_b         = NA_character_
  )

  append_expression_parquet(out, file.path(output_root, "01_HCA_all_celltypes"))
}

# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

#' Convert all three Williams MOESM workbooks, appending into existing folders.
#'
#' Delete any existing expression.parquet files before running to avoid
#' double-appending rows from a previous run.
#'
#' @param moesm2_path Path to MOESM2 (cluster marker genes) workbook.
#' @param moesm4_path Path to MOESM4 (DE region/age/sex) workbook.
#' @param moesm5_path Path to MOESM5 (cluster-wise DE) workbook.
#' @param output_root Root directory containing the existing lineage folders.
convert_williams_all <- function(
    moesm2_path,
    moesm4_path,
    moesm5_path,
    output_root = "data/Williams/snrna/conversions") {

  if (!requireNamespace("readxl", quietly = TRUE)) stop("readxl required")
  if (!requireNamespace("arrow",  quietly = TRUE)) stop("arrow required")

  message("=== MOESM2 (cluster markers) ===")
  convert_williams_MOESM2(moesm2_path, output_root)

  message("=== MOESM4 (DE region/age/sex) ===")
  convert_williams_MOESM4(moesm4_path, output_root)

  message("=== MOESM5 (cluster-wise DE) ===")
  convert_williams_MOESM5(moesm5_path, output_root)

  message("Done.")
}

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
if (sys.nframe() == 0) {
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) < 3)
    stop("Usage: Rscript williams_xlsx_to_parquet.R <moesm2.xlsx> <moesm4.xlsx> <moesm5.xlsx> [output_root]")

  convert_williams_all(
    moesm2_path = args[[1]],
    moesm4_path = args[[2]],
    moesm5_path = args[[3]],
    output_root = if (length(args) >= 4) args[[4]] else "data/Williams/snrna/conversions"
  )
}